name: Build
on: 
  push:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PATH: ${{ github.workspace }}/key.jks
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      BUILD_SIG: $GITHUB_RUN_NUMBER
    steps:
      - name: checkout current src
        uses: actions/checkout@v3
      - name: setup java env
        uses: actions/setup-java@v3
        with:
          java-version: 11 # using java 11
          distribution: adopt # using openjdk adopt
      - name: extract key store file from secret
        run: echo $KEY_JKS | base64 -di > key.jks
      - name: build
        run: ./gradlew build
      - name: this release name
        run: echo $GITHUB_RUN_NUMBER
      - name: create release # disable to save storage
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/**/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ format('build/{0}', env.BUILD_SIG) }}
          commit: ${{ github.sha }}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/**/app-release.apk
