name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current src
        uses: actions/checkout@v2
      - name: build
        run: ./gradlew build
